# El puerto donde correrá el BFF
server.port=8090

# Nombre de tu aplicación
spring.application.name=bff-mascotas

# URLs de los microservicios
ms.usuario.url=${MS_USUARIOS_URL:http://localhost:8081}
ms.mascota.url=${MS_MASCOTAS_URL:http://localhost:8082}
ms.reporte.url=${MS_REPORTES_URL:http://localhost:8083}

# La ruta de Swagger UI
springdoc.swagger-ui.path=/swagger

# URL del Frontend para CORS
frontend.url=${FRONTEND_URL:http://localhost:5173}