# El puerto donde correrá el BFF
server.port=8090

# Nombre de tu aplicación
spring.application.name=bff-mascotas

# URLs de los microservicios
ms.usuario.url=http://localhost:8081
ms.mascota.url=http://localhost:8082
ms.reporte.url=http://localhost:8083

# La ruta de Swagger UI
springdoc.swagger-ui.path=/swagger