# El puerto donde correrá el BFF (El que React va a consumir)
server.port=8090

# Nombre de tu aplicación
spring.application.name=bff-mascotas

# URLs de los microservicios locales (ajusta los puertos según los tengas configurados)
ms.auth.url=http://localhost:8091
ms.usuario.url=http://localhost:8091
ms.mascota.url=http://localhost:8091
ms.reporte.url=http://localhost:8091

# La ruta de Swagger UI
springdoc.swagger-ui.path=/swagger